### ISSUE TITLE
exception errors when starting up in Windows 10

### ISSUE THREAD

**Issue by avdjagt** [erwin-beckers/DayTradeScanner#3]
The application crashes due to exception errors, unexpected market values

**Comment by avdjagt** [comment]
System.IO.InvalidDataException
  HResult=0x80131501
  Message=Unexpected market name: IQXEOS
  Source=ExchangeSharp
  StackTrace:
   at ExchangeSharp.ExchangeBitfinexAPI.<OnGetSymbolsMetadataAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ExchangeSharp.ExchangeAPI.<GetSymbolsMetadataAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ExchangeSharp.ExchangeBitfinexAPI.<OnGetSymbolsAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ExchangeSharp.ExchangeAPI.<GetSymbolsAsync>d__36.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ExchangeSharp.ExchangeAPI.GetSymbols()
   at SPHScanner.Scanner.Scan(IStrategy strategy) in C:\Users\Arie\Downloads\SPHCryptoScanner-master2\SPHCryptoScanner-master\SPHScanner\Scanner.cs:line 26
   at SPHScanner.Program.Main(String[] args) in C:\Users\Arie\Downloads\SPHCryptoScanner-master2\SPHCryptoScanner-master\SPHScanner\Program.cs:line 30
